### PR TITLE
Remove unnecessary CSS and organice the styles

### PR DESCRIPTION
**Pull request by abdonrd**
Remove unnecessary CSS and organice the styles like the other paper-elements (applys separately from other styles)

This is in the iron-flex-layout:

```css
/* IE 10 support for HTML5 hidden attr */
[hidden] {		
  display: none !important;		
}
```

### CODE REVIEW

**Comment by notwaldorf** [comment]
I think this needs a rebase

**Comment by abdonrd** [comment]
Rebased. :)

**Comment by notwaldorf** [comment]
Turns out we should leave the `[hidden]` style in after all. The way html imports work is that the file is imported once, not in every element. This means that since this `hidden` doesn't have a '/deep/' style, it might not actually be in the same document scope as where the file was included.

**Comment by notwaldorf** [comment]
Closing this PR, since we should leave the style as it is.

**Comment by abdonrd** [comment]
Sorry, but I haven't understood very well.

Also, I've been tested in the demo and it seems to works:

screen shot 2015-12-16 at 11 09 18

**Comment by notwaldorf** [comment]
It works in the demo because you're using the shady DOM. The way HTML5 imports work is that `iron-flex-layout` is basically only requested once and it lives in the main document. So the main document has a `hidden` style, but that style isn't `/deep/`, so it isn't available in each of the elements' shadow roots. The shady DOM can't really enforce this encapsulation, so obviously the `hidden` selector works, but for it to work like that in the shadow DOM, it would have to be `html /deep/ hidden`, which is not encouraged.

**Comment by abdonrd** [comment]
@notwaldorf now I got it! Thanks for the explication! :sweat:

**Comment by notwaldorf** [comment]
No worries!

**Pull request closed without merging**
