### PR TITLE
Update bower file

### PR DESCRIPTION
**Pull request by BartKoppelmans**
Update `bower.json` to feature the latest version of `iron-image` (1.2.0)

### CODE REVIEW

**Comment by BartKoppelmans** [comment]
I signed it!

**Comment by notwaldorf** [comment]
Why is this change needed? Is `paper-card` using any changes from `1.2.0` specifically? Also, it should be using `iron-image#^1.2.0"`, not `~`

**Comment by BartKoppelmans** [comment]
It has the possibility to have a fallback for whenever the image fails to load. It has an error-event that fires whenever it can't load the image. This is useful, since my cards are sometimes failing to load the images and the placeholder should then switch to an error image.

**Comment by notwaldorf** [comment]
The fallback isn't being used (and the attribute is not exposed in `paper-card`'s public API), but the error event makes sense. Thanks!

**Pull request merged**
