### PR TITLE
Set all images to 600 width.

### LINKED ISSUE #59: Optimize Demo png files
@notwaldorf / @addyosmani look at optimizing `donuts.png` and `home.png`.   Paper-card went from 28.4 KB to 11.5 MB to download.

### PR DESCRIPTION
**Pull request by jfletcher-nuxeo**
To reduce the download footprint, set all images to 600 width to be consistent. Fixes #59.

### CODE REVIEW

**Comment by jfletcher-nuxeo** [comment]
I signed it!

On Tue, Feb 2, 2016 at 3:34 PM, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project. Before we can look at your
> pull request, you'll need to sign a Contributor License Agreement (CLA).
>
> [image: :memo:] *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PolymerElements/paper-card/pull/65#issuecomment-178885864>
> .
>



-- 

Josh Fletcher *Solutions Architect*
Twitter, Skype: jfletcher_nuxeo
+1-888-882-0969
nuxeo.com <https://www.nuxeo.com/>

[image: www.nuxeo.com - Content Management Platform] <http://www.nuxeo.com/>

**Comment by chuckh** [comment]
LGTM. @addyosmani or @notwaldorf PTAL.

**Comment by addyosmani** [comment]
LGTM. @notwaldorf wdyt?

**Comment by notwaldorf** [comment]
👍

**Pull request merged**
