### PR TITLE
Add image placeholder

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by honzalo** [comment]
Grate change :+1:, really looking forward this one.

It would be good to add a test case:

```javascript
test('placeholder properly setup', function() {
  assert.strictEqual(img.placeholder, null);
  f.placeholderImage = 'some-place-holder';
  assert.strictEqual(img.placeholder, f.placeholderImage);
});
```

**Comment by notwaldorf** [comment]
LGTM, but cc-ing @bicknellr in case he has any `iron-image` objections

**Comment by abdonrd** [comment]
Test added :)

**Comment by bicknellr** [comment]
No iron-image complaints, LGTM.

**Comment by notwaldorf** [comment]
Thanks!

**Comment by mgibas** [comment]
These changes should be a part of 1.1.1 release right ?

**Comment by abdonrd** [comment]
@mgibas no. :/

**Comment by mgibas** [comment]
Ok, my bad - for 1.1.1 I read  Jun 27  instead JAN :/

**Pull request merged**
