### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by M0nter0**
Update link to material-design card page spec

### CODE REVIEW

**Comment by M0nter0** [comment]
I 've just signed the Contributor License Agreement (CLA)

**Comment by notwaldorf** [comment]
@M0nter0 could you reply with `I signed it!` to appease the clabot, please?

**Comment by M0nter0** [comment]
I signed it!

**Comment by notwaldorf** [comment]
@M0nter0 Gah, can you maybe try signing it again? I checked our list of signers and you're not on it :(

**Comment by M0nter0** [comment]
I signed it!

**Comment by notwaldorf** [comment]
@M0nter0 Arg, I'm sorry, while I was waiting for this I seem to have accidentally merged the same fix from https://github.com/PolymerElements/paper-card/pull/7. Sorry!

**Comment by M0nter0** [comment]
No problem!

**Pull request closed without merging**
