### PR TITLE
fix margin

### PR DESCRIPTION
**Pull request by alirni**
fix margin 3px paper-card for demo view

### CODE REVIEW

**Comment by notwaldorf** [comment]
Why is this change needed?

**Comment by alirni** [comment]
because paper card class="cyan" out of div id="notes"

**Comment by alirni** [comment]
screenshot 2016-10-17 09 03 18

**Comment by alirni** [comment]
@notwaldorf  hi!
you see screenshot?

**Comment by notwaldorf** [comment]
Sure. I can't repro this on the mac but maybe there's a weird pixel rounding thing on some Windows. It's fine either way

**Pull request merged**
