### PR TITLE
prettify demo

### PR DESCRIPTION
**Pull request by notwaldorf**
OH MAN! Basically changed all the things, and did a lot of examples from the spec. Here's all of them:
screen shot 2016-01-15 at 12 33 39 pm
screen shot 2016-01-15 at 12 33 43 pm
screen shot 2016-01-15 at 12 33 49 pm
screen shot 2016-01-15 at 12 34 03 pm
screen shot 2016-01-15 at 12 34 12 pm
screen shot 2016-01-15 at 12 34 25 pm

### CODE REVIEW

**Comment by abdonrd** [comment]
These demonstrations are amazing! :scream:

**Comment by kbwatts** [comment]
Really nice!

**Comment by BartKoppelmans** [comment]
This looks great! Absolutely has the material design spirit!

**Comment by addyosmani** [comment]
These look fantastic, @notwaldorf. The only comment I had was color contrast between the text and background images could maybe be tweaked but that may be overkill to worry about for demos. That aside, this LGTM for a land.

**Comment by addyosmani** [comment]
Closed via https://github.com/PolymerElements/paper-card/commit/203e1fce5d3ec3396645234b3d687ecf020e633f

**Pull request closed without merging**
