### PR TITLE
Add shadow dom test configurations

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by notwaldorf** [comment]
@rictic should i merge this?

**Comment by rictic** [comment]
Yes, though it's worth noting that this will cause the tests to start failing.

Chris and I were going with a plan to take a quick look and file a bug then merge these PRs. Then other things happened. :disappointed:

https://docs.google.com/spreadsheets/d/166pE8UwkJQwtUzirEv03kDYQmilKO0-ggZBrrzyDh9g/edit#gid=0 is the burn down spreadsheet

**Comment by notwaldorf** [comment]
Oh! I get it. I'll look at the tests tomorrow!

**Comment by notwaldorf** [comment]
Opened #49 (and I'll fix the other ones too)

**Comment by notwaldorf** [comment]
Actually, i'll close this PR and add the test in #49, so i can test what i fixed :)

**Pull request closed without merging**
