### PR TITLE
Update version to 1.0.5

### PR DESCRIPTION
**Pull request by JeremybellEU**
Update the paper-card to 1.0.5 so we can use the new styling of paper-material which we need for our element.

### CODE REVIEW

**Comment by JeremybellEU** [comment]
I signed it!

**Comment by notwaldorf** [comment]
I will do this manually and cut a release. As a note, the mixin documentation you added  is not correct `--layout-fit`is an existing mixin applied to that selector. The `Styling` documentation block lists mixins that are available for the user to define

**Comment by JeremybellEU** [comment]
Okay, I am sorry for being mistaken. Thanks for releasing the new version though!

**Comment by notwaldorf** [comment]
@JeremybellEU No worries! Thanks for reminding me about the release :)

**Comment by JeremybellEU** [comment]
:+1: Don't want to be bothersome, but could you update https://github.com/PolymerElements/paper-elements/blob/master/bower.json#L30 too? Else I will just manually select the paper-card version in the resolutions in our bower.json.

**Comment by notwaldorf** [comment]
That line says "pick the latest paper-card version available", so it should pick up 1.0.5. A `bower install` should pick it up. Sometimes bower is grumpy and needs a `bower cache clean` first to jiggle its memory.

**Comment by JeremybellEU** [comment]
Ah TIL. Many thanks again and have fun defeating dragons! #summit #cooltalks

**Pull request closed without merging**
